# Generated by Django 3.1.4 on 2021-01-04 07:52

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(editable=False, max_length=16, unique=True)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email_id', models.EmailField(max_length=256)),
                ('mobile_number', models.CharField(max_length=10)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'db_table': 'employee_details',
            },
        ),
    ]
